### ISSUE TITLE
Implement the parser

### ISSUE THREAD

**Issue by Abdurrahman-Salah-ad-Din** [CheeseCake-Team/ChickenMasala#7]
# Task

You have to take the meals from the *.csv* file.
__Note:__ Every single line in the *.csv* file represents a meal.

## implement the parser
- [ ] put the *.csv* file in the project.
- [ ] complete the `CsvDataSource` class.
- [ ] complete the `CsvParser` class.
